"""add_performance_indices

Revision ID: fc169c5093f5
Revises: 3ba67bc677b8
Create Date: 2026-07-20 09:59:08.191070

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fc169c5093f5'
down_revision: Union[str, Sequence[str], None] = '3ba67bc677b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_code_chunks_file_id', 'code_chunks', ['file_id'], unique=False)
    op.create_index('idx_code_embeddings_chunk_id', 'code_embeddings', ['chunk_id'], unique=False)
    op.create_index('idx_dependency_edges_source_file_id', 'dependency_edges', ['source_file_id'], unique=False)
    op.create_index('idx_dependency_edges_target_file_id', 'dependency_edges', ['target_file_id'], unique=False)
    op.create_index('idx_symbols_file_id', 'symbols', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_symbols_file_id', table_name='symbols')
    op.drop_index('idx_dependency_edges_target_file_id', table_name='dependency_edges')
    op.drop_index('idx_dependency_edges_source_file_id', table_name='dependency_edges')
    op.drop_index('idx_code_embeddings_chunk_id', table_name='code_embeddings')
    op.drop_index('idx_code_chunks_file_id', table_name='code_chunks')
    # ### end Alembic commands ###
