from pathlib import Path

from app.analysis.ignore import should_ignore_file
from app.analysis.languages import Language, detect_language_from_path
from app.analysis.test_detector import TestDetector


class FileClassifier:
    """Classify repository files before indexing."""

    GENERATED_MARKERS = {
        "generated",
        "autogenerated",
        "auto-generated",
        "do not edit",
        "@generated",
    }

    GENERATED_SUFFIXES = {
        ".min.js",
        ".map",
        ".lock",
        ".snap",
    }

    def __init__(self, test_detector: TestDetector | None = None) -> None:
        self.test_detector = test_detector or TestDetector()

    def classify(
        self,
        file_path: str | Path,
        content: str | bytes | None = None,
    ) -> dict[str, object]:
        """Return indexing metadata for a tracked file."""
        path = Path(file_path).as_posix()
        text = self._decode_content(content)
        language = detect_language_from_path(path)
        return {
            "path": path,
            "language": language,
            "is_supported": language is not Language.UNKNOWN,
            "is_test": self.test_detector.is_test_file(path, text),
            "is_generated": self.is_generated_file(path, text),
            "should_ignore": should_ignore_file(path),
            "loc": self.count_loc(text),
        }

    def is_generated_file(
        self, file_path: str | Path, content: str | bytes | None = None
    ) -> bool:
        """Detect common generated files without executing repository code."""
        path = Path(file_path).as_posix().lower()
        name = Path(path).name
        if any(name.endswith(suffix) for suffix in self.GENERATED_SUFFIXES):
            return True
        if "/generated/" in f"/{path}" or "/__generated__/" in f"/{path}":
            return True

        text = self._decode_content(content).lower()
        header = "\n".join(text.splitlines()[:8])
        return any(marker in header for marker in self.GENERATED_MARKERS)

    def count_loc(self, content: str | bytes | None) -> int:
        """Count non-empty source lines."""
        text = self._decode_content(content)
        return sum(1 for line in text.splitlines() if line.strip())

    def _decode_content(self, content: str | bytes | None) -> str:
        if content is None:
            return ""
        if isinstance(content, bytes):
            return content.decode("utf-8", errors="replace")
        return content
